"""Alembic migration environment.

The database URL always comes from the application settings
(``DATABASE_URL`` via pydantic-settings) — never hardcoded here.
``target_metadata`` is the Sales Agent application metadata ONLY; LangGraph
checkpoint tables are managed by ``langgraph-checkpoint-postgres`` itself and
must not appear here (architecture audit §L).
"""

from logging.config import fileConfig

from alembic import context
from sqlalchemy import pool

from app.config.settings import Settings, get_settings
from app.models import Base  # imports all models -> populates Base.metadata

# Alembic Config object (provides access to alembic.ini values).
config = context.config

if config.config_file_name is not None:
    fileConfig(config.config_file_name)

target_metadata = Base.metadata


def _get_url() -> str:
    """Resolve the sync database URL from application settings.

    Alembic runs synchronously and needs a psycopg3 driver URL. If the user
    supplied a driverless ``postgresql://`` URL, upgrade it to
    ``postgresql+psycopg://`` so Alembic uses the same driver as the app.
    """
    settings: Settings = get_settings()
    url = settings.sqlalchemy_database_uri
    if url.startswith("postgresql://"):
        url = url.replace("postgresql://", "postgresql+psycopg://", 1)
    return url


def run_migrations_offline() -> None:
    """Emit SQL to stdout without a DB connection (``--sql`` mode)."""
    context.configure(
        url=_get_url(),
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        compare_type=True,
    )
    context.run_migrations()


def run_migrations_online() -> None:
    """Run migrations with a live connection."""
    from sqlalchemy import create_engine

    connectable = create_engine(_get_url(), poolclass=pool.NullPool)
    with connectable.connect() as connection:
        context.configure(
            connection=connection,
            target_metadata=target_metadata,
            compare_type=True,
            # Recognize this app's metadata; LangGraph checkpoint tables are
            # intentionally outside of it and will never be dropped/autogenerated.
            version_table="alembic_version",
        )
        context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
